---
- name: "Copy config file"
  notify: "(Re)start and enable Alertmanager"
  ansible.builtin.copy:
    src: "{{ config_source_dir }}/alertmanager.yml"
    dest: "{{ config_dir }}/alertmanager.yml"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: "0660"

- name: "Copy templates if existed"
  notify: "(Re)start and enable Alertmanager"
  when: template_source_dir is defined
  ansible.builtin.copy:
    src: "{{ template_source_dir }}/{{ item }}"
    dest: "{{ config_dir }}/alertmanager.yml"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: "0660"
  with_fileglob:
    "{{ template_source_dir }}/*tmpl"
