---
- name: "Create AlertManager system group"
  ansible.builtin.group:
    name: "{{ alertmanager_user }}"
    system: true
    state: present

- name: "Create AlertManager system user"
  ansible.builtin.user:
    name: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    system: true
    shell: "/sbin/nologin"
    create_home: false
    state: present

- name: "Install AleertManager from binary"
  block:
    - name: "Check AlertManager version"
      changed_when: false
      ansible.builtin.command:
        cmd: "alertmanager --version"
      register: alertmanager_ver

    - name: "Assert version correctness"
      ansible.builtin.assert:
        that: "alertmanager.stdout is regex('{{ alertmanager_version }}')"
        success_msg: "alertmanager version {{ alertmanager_version }} is installed and working"
        fail_msg: "alertmanager version {{ alertmanager_version }} is not installed or not working correctly"

  rescue:
    - name: "Create prometheus directories {{ item }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: "0755"
      with_items:
        - "{{ config_dir }}"
        - "{{ prometheus_dir }}"
        - "{{ db_dir }}"

    - name: "Download Prometheus binary"
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/\
              alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus-{{ alertmanager_version }}.linux-amd64.tar.gz"
        owner: "{{ alertmanager_user }}"
        group: "{{ alertmanager_group }}"
        mode: "0644"

    - name: "Unpack Prometheus binaries"
      ansible.builtin.unarchive:
        src: "/tmp/prometheus-{{ alertmanager_version }}.linux-amd64.tar.gz"
        dest: "{{ alertmanager_dir }}"
        creates: "{{ alertmanager_dir }}/prometheus-{{ alertmanager_version }}.linux-amd64"
        remote_src: true

    - name: "Cleanup downloaded file"
      ansible.builtin.file:
        path: "/tmp/prometheus-{{ alertmanager_version }}.linux-amd64.tar.gz"
        state: absent

    - name: "Move official alertmanager and amtool binaries"
      ansible.builtin.copy:
        src: "{{ alertmanager_dir }}/prometheus-{{ alertmanager_dir }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: "0755"
        owner: "{{ alertmanager_user }}"
        group: "{{ alertmanager_group }}"
        remote_src: true
      with_items:
        - alertmanager
        - amtool

    - name: "Create config file"
      ansible.builtin.template:
        src: "{{ config_source_dir }}/alertmanager.yml"
        dest: "{{ config_dir }}/alertmanager.yml"
        owner: "{{ alertmanager_user }}"
        group: "{{ alertmanager_group }}"
        mode: "0660"

    - name: "Create systemd service unit"
      ansible.builtin.template:
        src: alertmanager.service.j2
        dest: /etc/systemd/system/alertmanager.service
        owner: "{{ alertmanager_user }}"
        group: "{{ alertmanager_group }}"
        mode: "0660"

    - name: "Make sure that the alertmanager are enabled and started"
      become: true
      ansible.builtin.systemd:
        name: alertmanager.service
        state: started
        enabled: true
        daemon_reload: true
