global:
  # SMTP configuration for email notifications (if needed)
  smtp_smarthost: 'mailserver.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'your_password'

  # Other global settings like resolve_timeout, http_config, etc.

route: 
  # Default receiver for alerts
  receiver: 'default-receiver'

  # Labels used for grouping alerts 
  group_by: ['alertname', 'instance', 'severity'] 

  # Timing settings (group_wait, group_interval, repeat_interval) 
  # You can have nested 'routes' for more complex routing logic 

receivers:
- name: 'default-receiver'
  email_configs:
    to: 'ops-team@example.com' 
    # ... other email settings ...

- name: 'slack-notifications'
  slack_configs:
    api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#alerts'
    # ... other Slack settings ...

- name: 'pagerduty-notifications'
  pagerduty_configs:
    service_key: 'your_pagerduty_service_key'
    # ... other PagerDuty settings ...

# ... more receivers as needed (webhooks, OpsGenie, etc.)

inhibit_rules:
  # Rules to suppress alerts based on other alerts
  # Example:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    # Suppress 'warning' alerts if a 'critical' alert is also firing

templates: 
  # Paths to template files for customizing notifications 
  - '/etc/alertmanager/templates/*.tmpl' 